- crux/models/dataset.py
- crux/models/file.py
- crux/models/folder.py
- crux/models/query.py
- crux/models/resource.py
- crux/models/table.py
- tests/unit/test_dataset.py
- Added read attribute path for resource model.
- Refactored folder attribute for resource model.
- Refactored dataset methods to support new folder attribute behaviour.
- Refactored File, Folder, Query, Table models to support new behaviour.
* Ran `make test` and all tests passed.
```bash
nox > Ran multiple sessions:
nox > * type_check-3.7: success
```
> Added path and folder attributes.

- crux/models/resource.py
- Refactor size attribute for resource model.
* Ran make test and all tests passed.
```bash
nox > Ran multiple sessions:
nox > * type_check-3.7: success
```
> Size attribute for resource

- crux/models/dataset.py
- crux/models/identity.py
- crux/models/job.py
- crux/models/permission.py
- crux/models/resource.py
- Removed property setters in Dataset model so that they are read-only.
- Removed property setters in Identity model so that they are read-only. Added phone property.
- Removed property setters in Job model so that they are read-only.
- Removed property setters in Permission model so that they are read-only.
- Removed property setters in Resource model so that they are read-only. Added size property.
* Ran make test and all tests passed.
```bash
nox > Ran multiple sessions:
nox > * type_check-3.7: …
```
> Remove setters for read-only model attributes.

- Pipfile
- Pipfile.lock
- crux/apis.py
- crux/config.py
- crux/models/dataset.py
- crux/models/file.py
- crux/models/query.py
- crux/models/resource.py
- crux/models/table.py
- crux/utils.py
- noxfile.py
- requirements-dev.txt
- requirements.txt
- setup.py
- tests/integration/test_labels.py
- tests/unit/test_config.py
- tests/unit/test_resource.py
- tests/unit/test_utils.py
* Added google resumable media support for `file` resource model.
* Removed `download()` function from `resource` model to adhere Liskov principle. Added `download()` method to individual `resource` subtypes.
* Added utility function to convert string to boolean.
* Added and Refactored unit and integration tests.
* Ran `make unit` and `make lint` and it passed.
> Add Resumable Signed URL support.

- crux/models/dataset.py
- crux/models/file.py
- crux/models/resource.py
- crux/models/table.py
- crux/utils.py
- docs/stitching.md
- tests/unit/test_dataset.py
- tests/unit/test_utils.py
* Refactor variable content_type -> media_type.
* Refactor variable from ContentType -> MediaType.
* Ran `make test` and tests passed.
```bash
nox > * type_check-3.7: success
```
> Refactor content_type to media_type.

- crux/client.py
- docs/downloading.md
* Refactored code to use Session instead of [deprecated](https://github.com/requests/requests/blob/master/requests/sessions.py#L758) session.
* Ran make test and tests passed.
```bash
nox > * type_check-3.7: success
```
> Refactor session -> Session

- crux/apis.py
* To correct compatibility, changed the `unicode` type to `text` type.
* Ran `make lint` and `make unit` and it passed.
> Refactor Unicode -> Text.

- crux/apis.py
- crux/models/dataset.py
- tests/integration/test_dataset.py
* Added support to fetch provenance list for given Dataset object.
* Ran `make lint` and `make test` and it passed.
> Add Provenance support.

- crux/__init__.py
- crux/_client.py
- crux/_config.py
- crux/models/__init__.py
- crux/models/dataset.py
- crux/models/file.py
- crux/models/folder.py
- crux/models/table.py
- docs/index.md
- docs/logging.md
- tests/integration/test_dataset.py
* Added info and debug log levels.
* Updated provenance key workflow_id, cron_spec to workflowId, CronSpec, in the test.
* Refactored code to use unicode where it type matching to string.
* Ran `make lint` and `make test`, it passed.
> Added logging functionality.

- crux/_utils.py
- crux/models/dataset.py
- crux/models/file.py
- crux/models/resource.py
- tests/integration/conftest.py
- tests/integration/test_dataset.py
- tests/integration/test_file.py
* Added custom Session class to support signed urls.
* Refactored Dataset and File upload mechanism to support both resumable and current implementation.
* Set the default size of any created resource to 0 instead of None.
* Refactored test cases.
* Added test cases which uses crux domain.
* Ran `make lint` and `make unit`, it passed.
> Add GCS upload support.

- README.md
- crux/__version__.py
- docs/index.md
- docs/installation.md
Changes:
- Add support for direct from GCS downloads
- Add pagination to label search
- Add logging functionality
- Fix bug that prevented small files from being downloaded directly
from GCS
Breaking changes:
- Rename some required args in download/upload methods to improve
accuracy of arg names
> Bump version to 0.0.4

- README.md
- crux/__version__.py
- docs/index.md
- docs/installation.md
Changes:
- Fix setup.py to support Python 2.7
> Bump version to 0.0.5

- README.md
- crux/__version__.py
- docs/index.md
- docs/installation.md
Changes:
- Add `Crux.get_resource()` to get resources by ID.
> Bump version to 0.0.7

- crux/_config.py
- crux/models/resource.py
- docs/labels.md
- tests/integration/test_labels.py
- tests/unit/test_resource.py
Added a new method `add_labels` to the `Resource` model for adding labels in batch.
Included two unit tests, an integration test, and documentation updates.
> Add multiple labels at once to a resource

- README.md
- crux/__version__.py
- docs/index.md
- docs/installation.md
Changes:
- Add `Resource.add_labels()` to support adding multiple labels in one
API call.
> Bump version to 0.0.8

- Pipfile.lock
- crux/models/resource.py
- requirements-dev.txt
- requirements.txt
- Updated Pipfile.lock
- Regenerated requirements-dev.txt and requirements.txt
- Reformatted unformatted `resource.py`
- `make format`, `make lint`, `make unit`, `make integration` and `make docs` passed.
> Updated python dependencies

- crux/__init__.py
- crux/_client.py
- crux/_config.py
- crux/_utils.py
- crux/models/dataset.py
- crux/models/file.py
- crux/models/folder.py
- crux/models/resource.py
- crux/models/table.py
- docs/logging.md
- Removed logging of request headers and payload data.
- Formatted code with `$ make format`.
* Lint, Unit and Integration tests passed.
> Added TRACE support for crux-python.

- crux/models/resource.py
- tests/unit/test_resource.py
Support for updating resource provenance after a resource has been created.
> add support to update resource provenance

- README.md
- crux/__version__.py
- docs/index.md
- docs/installation.md
Changes:
- Add support for TRACE log level for logging sensitive information.
- Add support for updating resource provenance.
> Bump version to 0.0.9

- README.md
- crux/__version__.py
- docs/index.md
- docs/installation.md
Changes:
- Add support for API client deep copy for Python 3.6.6 [Python Issue tracker: 10076](https://bugs.python.org/issue10076)
> Bump version to 0.0.10

- README.md
- crux/__version__.py
- docs/index.md
- docs/installation.md
Changes:
Add support for explicitly raising an execution on file download failure.
Add flag for using crux domains/content uploads/downloads for resource  upload/download
> Bump version to 0.0.11

- README.md
- crux/__version__.py
- docs/index.md
- docs/installation.md
Changes:
- Fix client to support passing API key as an arg.
- Fix models to allow connection to be replaced after instantiating.
- Add ingestion and delivery interfaces.
> Bump version to 0.0.13

- crux/_utils.py
- crux/models/resource.py
- infra-515 - Remove config property from Resource
- infra-683 - regex fix
> Small cleanup

- README.md
- crux/__version__.py
- docs/_release_process.md
- docs/index.md
- docs/installation.md
Breaking Changes:
- Convert List Resources call to a generator
- Use paginated resource calls endpoint `plat-api/resources` with filters for list resources
Changes:
- Update Parquet data type for fetching delivery resources
- add utility endpoint to get latest ingestion
> bump version to 0.0.14

- README.md
- crux/__version__.py
- docs/_release_process.md
- docs/index.md
- docs/installation.md
Bump version to 0.0.15
BREAKING CHANGES:
- None
Changes:
- add dataset properties
- add get_files_range()
- add get_latest_files()
> bump version to 0.0.15

- requirements-dev.txt
- requirements.txt
Need sphinx <3.0.0 as there are breaking changes
> update requirements-dev.txt for readthedocs

- crux/models/dataset.py
- docs/dataset.md
https://cruxinformatics.atlassian.net/browse/AUT-279
> Cutoff date for get_latest_files()

- crux/apis.py
- crux/models/dataset.py
fix list datasets limit
get latest files by frame as there can be different deliveries for different frames
> latest files by frame

- README.md
- crux/__version__.py
- docs/_release_process.md
- docs/index.md
- docs/installation.md
Changes:
- fix list datasets limit
- get latest files by frame as there can be different deliveries for different frames
> bump version version to 0.0.19

- README.md
- crux/__version__.py
- docs/_release_process.md
- docs/index.md
- docs/installation.md
Changes:
- Re-release due to bad whl
> Bump version to 0.0.20

- crux/_client.py
- crux/_config.py
> Support v2 api prefix

- README.md
- crux/__version__.py
- docs/_release_process.md
- docs/index.md
- docs/installation.md
**BREAKING CHANGES:**
- None
**Changes:**
- Support v2 api prefix /v2
> bump version to 0.0.21

- crux/models/dataset.py
- tests/regression/client.py
- handle edge case where supplier_implied_dt is always 1Q older than the ingestion_dt
- look back for all time if necessary for get_latest_files
> fix get_latest_files()

- README.md
- crux/__version__.py
- docs/_release_process.md
- docs/index.md
- docs/installation.md
BREAKING CHANGES:
- None
Changes:
- Fix get_latest_files()
- Streamline documentation
> bump version to 0.0.22

- README.md
- docs/index.md
- Bump version to 1.1 on release
- Update documentation intro
> Update documentation to reflect full release status

- README.md
- crux/__version__.py
- docs/_release_process.md
- docs/index.md
- docs/installation.md
Bump version to 1.1
Changes:
- Update documentation to reflect full production status
> bump version to 1.1

- crux/_client.py
- crux/_config.py
- crux/_utils.py
- crux/apis.py
- crux/models/dataset.py
GE-158 get_latest_files date fix
> GE-158  get_latest_files date fix

- README.md
- docs/_release_process.md
- docs/index.md
- docs/installation.md
Bump version to 1.2
BREAKING CHANGES:
- None
Changes:
- Use v1/client for some calls instead of plat-api
- bug fix for get_latest_files method
> Bump version to 1.2

- crux/_client.py
- crux/apis.py
- crux/models/dataset.py
- crux/models/delivery.py
- crux/models/resource.py
- docs/index.md
[integ-4443] remove plat-api calls
> [integ-4443] remove plat-api calls
